-- level4
-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

WITH AVAILABLE AS (
    SELECT CAR_ID,
           SUM(IF (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30', 0, 1)) AS TEMP
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     GROUP BY CAR_ID
    HAVING TEMP = 0
)

SELECT C.CAR_ID AS CAR_ID
     , C.CAR_TYPE AS CAR_TYPE
     , TRUNCATE(C.DAILY_FEE * 30 * ((100 - DP.DISCOUNT_RATE) / 100), 0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C
  JOIN AVAILABLE A
    ON C.CAR_ID = A.CAR_ID
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
 WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') AND
       TRUNCATE(C.DAILY_FEE * 30 * ((100 - DP.DISCOUNT_RATE) / 100), 0) >= 500000 AND
       TRUNCATE(C.DAILY_FEE * 30 * ((100 - DP.DISCOUNT_RATE) / 100), 0) < 2000000
 ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;