-- level4
-- https://school.programmers.co.kr/learn/courses/30/lessons/131532

SELECT YEAR(OS.SALES_DATE) AS YEAR
     , MONTH(OS.SALES_DATE) AS MONTH
     , UI.GENDER AS GENDER
     , COUNT(DISTINCT UI.USER_ID) AS USERS
     
  FROM USER_INFO UI
  JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
    
 WHERE GENDER IS NOT NULL
 
 GROUP BY YEAR, MONTH, GENDER
 
 ORDER BY YEAR, MONTH, GENDER;
    
    