-- level3 
-- https://school.programmers.co.kr/learn/courses/30/lessons/293261

SELECT I.ID AS 'ID'
     , NI.FISH_NAME AS 'FISH_NAME'
     , I.LENGTH AS 'LENGTH'
  FROM FISH_INFO I
  JOIN FISH_NAME_INFO NI
    ON I.FISH_TYPE = NI.FISH_TYPE
  JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
          FROM FISH_INFO
         GROUP BY FISH_TYPE) SUB
    ON NI.FISH_TYPE = SUB.FISH_TYPE
 WHERE I.LENGTH = SUB.MAX_LENGTH
 ORDER BY I.ID;