-- level2
-- https://school.programmers.co.kr/learn/courses/30/lessons/299310

SELECT SUB.YEAR AS YEAR
     , (SUB.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV
     , ED.ID
  FROM ECOLI_DATA ED
  JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS `YEAR`
             , MAX(SIZE_OF_COLONY) AS MAX_SIZE
          FROM ECOLI_DATA
         GROUP BY YEAR(DIFFERENTIATION_DATE)) SUB
    ON YEAR(ED.DIFFERENTIATION_DATE) = SUB.YEAR
 ORDER BY SUB.YEAR, YEAR_DEV;