-- level4
-- https://school.programmers.co.kr/learn/courses/30/lessons/144856

SELECT A.AUTHOR_ID AS AUTHOR_ID
     , A.AUTHOR_NAME AS AUTHOR_NAME
     , B.CATEGORY AS CATEGORY
     , SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
  FROM BOOK B
  JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
  JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
 WHERE YEAR(BS.SALES_DATE) = 2022 AND 
       MONTH(BS.SALES_DATE) = 1
 GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
 ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;